knpu_oauth2_client:

    clients:

        facebook: 
            type: facebook
            client_id: '%env(OAUTH_FACEBOOK_ID)%'
            client_secret: '%env(OAUTH_FACEBOOK_SECRET)%'
            redirect_route: Facebook_Check
            redirect_params: {}
            graph_api_version: v2.12

        github:
            type: github
            client_id: '%env(OAUTH_GITHUB_CLIENT_ID)%'
            client_secret: '%env(OAUTH_GITHUB_CLIENT_SECRET)%'
            redirect_route: Github_Check
            redirect_params: {}
            # use_state: true