security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        user:
            entity:
                class: App\Entity\User
                property: email
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            remember_me:
                secret: '%kernel.secret%'
            access_denied_handler: App\Security\AccessDeniedHandler
            provider: user
            guard:
                authenticators:
                    - App\Security\Guard\UserAuthenticator
                    - App\Security\Guard\OauthAuthenticator
                entry_point: App\Security\Guard\UserAuthenticator
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/login, allow_if: "not is_granted('ROLE_USER')" }
        - { path: ^/signup, allow_if: "not is_granted('ROLE_USER')" }
        - { path: ^/forgot, allow_if: "not is_granted('ROLE_USER')" }
        - { path: ^/reset, allow_if: "not is_granted('ROLE_USER')" }
        - { path: ^/api, allow_if: "is_fully_authenticated()" }
        - { path: ^/boards, allow_if: "is_fully_authenticated()" }
        - { path: ^/board, allow_if: "is_fully_authenticated()" }        
        - { path: ^/profile, allow_if: "is_fully_authenticated()" }