#   Dashboard
# ----------------------------------#

Boards:
    path: /dashboard
    controller: App\Controller\DashController::boards

Board:
    path: board/{slug}
    controller: App\Controller\DashController::board

Profile:
    path: /dashboard/profile
    controller: App\Controller\DashController::profile