#   Rest API
# ----------------------------------#

GetUsers:
    path: /api/getusers
    controller: App\Controller\RestController::getUsers

GetList:
    path: /api/getlist
    controller: App\Controller\RestController::getList

ModList:
    path: /api/modlist
    controller: App\Controller\RestController::modList

ModTask:
    path: /api/modtask
    controller: App\Controller\RestController::modTask

DeleteUser:
    path: /api/deleteuser
    controller: App\Controller\RestController::deleteUser