#   Utilities
# ----------------------------------#

ContactForm:
    path: /contactform
    controller: App\Controller\UtilityController::contactForm

ConfirmEmail:
    path: /confirm
    controller: App\Controller\UtilityController::confirmEmail