#   Frontend
# ----------------------------------#

Home:
    path: /
    controller: App\Controller\FrontController::home

About:
    path: /about
    controller: App\Controller\FrontController::about

Contact:
    path: /contact
    controller: App\Controller\FrontController::contact

Terms:
    path: /terms
    controller: App\Controller\FrontController::terms

Privacy:
    path: /privacy
    controller: App\Controller\FrontController::privacy


#   Authentication
# ----------------------------------#

Signup:
    path: /signup
    controller: App\Controller\AuthController::signup

Login:
    path: /login
    controller: App\Controller\AuthController::login

Logout:
    path: /logout

Forgot:
    path: /forgot
    controller: App\Controller\AuthController::forgot

Change:
    path: /change
    controller: App\Controller\AuthController::change


#   Dashboard
# ----------------------------------#

Lists:
    path: /dashboard
    controller: App\Controller\DashController::lists

List:
    path: list/{slug}
    controller: App\Controller\DashController::list

Profile:
    path: /dashboard/profile
    controller: App\Controller\DashController::profile


#   Utilities
# ----------------------------------#

ContactForm:
    path: /contactform
    controller: App\Controller\UtilityController::contactForm

ConfirmEmail:
    path: /confirm
    controller: App\Controller\UtilityController::confirmEmail



#   Rest API
# ----------------------------------#

GetUsers:
    path: /api/getusers
    controller: App\Controller\RestController::getUsers

GetList:
    path: /api/getlist
    controller: App\Controller\RestController::getList

ModList:
    path: /api/modlist
    controller: App\Controller\RestController::modList

ModTask:
    path: /api/modtask
    controller: App\Controller\RestController::modTask