# Frontend

Home:
    path: /
    controller: App\Controller\FrontController::home

About:
    path: /about
    controller: App\Controller\FrontController::about

Contact:
    path: /contact
    controller: App\Controller\FrontController::contact

Terms:
    path: /terms
    controller: App\Controller\FrontController::terms

Privacy:
    path: /privacy
    controller: App\Controller\FrontController::privacy


# Authentication

Login:
    path: /login
    controller: App\Controller\AuthController::login

Signup:
    path: /signup
    controller: App\Controller\AuthController::signup

Logout:
    path: /logout


# Dashboard

Lists:
    path: /dashboard
    controller: App\Controller\DashController::lists

Profile:
    path: /dashboard/profile
    controller: App\Controller\DashController::profile