App\Entity\User: 
    subresource: 
        resourceClass: App\Entity\Board
        collection: true
    itemOperations: 
        get: ~
        put: ~
        delete: ~
        check_password: ~
        encrypt_password: ~
        mailer: ~